version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/nginx-proxy/conf:/etc/nginx/conf.d:ro
      - ~/nginx-proxy/certs:/etc/nginx/certs:ro
    networks:
      BNSS-subnet:
        ipv4_address: 172.20.0.5


networks:
  BNSS-subnet:
    external: true