version: "3.9"

networks:
  BNSS-subnet:
    external: true

services:
  nextcloud:
    image: nextcloud:28.0.2
    container_name: nextcloud_critical
    restart: unless-stopped

    networks:
      BNSS-subnet:
        ipv4_address: 172.20.0.3

    volumes:
      - ~/nextcloud-critical-config/config.php:/usr/src/nextcloud/config/config.php:ro

volumes:
  nextcloud_data: