local-data: "secret.acme.internal IN A 192.168.40.5"
local-data: "fileshare.acme.internal IN A 192.168.40.5"
local-data: "ca.acme.internal IN A 192.168.40.5"
local-data: "ldap.acme.internal IN A 192.168.40.6"

